root = "."
tmp_dir = "tmp"


[build]
cmd = "go build -o ./tmp/main.exe ./cmd/server/main.go"
bin = "tmp\\main.exe"
delay = 1_000
exclude_dir = [ "assets", "tmp", "vendor", "testdata", "api/docs" ]
exclude_regex = [ "_test.go" ]
include_ext = [ "go", "yaml", "yml", "tpl", "tmpl", "html" ]
log = "build-errors.log"


[color]
app = "bright_blue"
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"


[log]
time = true
main_only = false


[misc]
clean_on_exit = true


[screen]
clear_on_rebuild = true
keep_scroll = true
